### ISSUE TITLE
Solver fails to converge for simple case

### ISSUE THREAD

**Issue by machml** [srnogueira/laine#6]
Caro, 
descobri um caso relativamente simples que o solver nao consegue resolver ("Error: Difficult (or unsolvable) problem").

Trata-se do item (a) do excercício complementar 1 de reacoes químicas (VanWylen 8ed 13.143):

"Consider the steady-state combustion of propane at 25°C with air at 400 K. The products exit the combustion chamber at 1200 K. Assume that the efficiency is 90% and that 95% of the carbon in the propane burns to form CO2 ; the remaining 5% forms CO. Determine (a) the ideal fuel–air ratio and (b) the heat transfer from the combustion chamber."

```
T1 = 298
T2 = 400
T3 = 1200

hc3h8_R=NasaSI('H0molar',T1,'C3H8')

ho2_R=NasaSI('H0molar',T2,'O2')
hn2_R=NasaSI('H0molar',T2,'N2')

hco2_P=NasaSI('H0molar',T3,'CO2')
hh2o_P=NasaSI('H0molar',T3,'H2O')
ho2_P=NasaSI('H0molar',T3,'O2')
hn2_P=NasaSI('H0molar',T3,'N2')

a = 5

hp = 3 * hco2_P + 4 * hh2o_P + 3.76 * a * s * hn2_P + a * (s-1) * ho2_P
hr = hc3h8_R + a * s * ( ho2_R + 3.76 * hn2_R )
hp = hr

# s = 3.169
```
Por ora, só vejo 2 workarounds, de curto e médio prazo respectivamente: (1) resolver iterativamente via trial-and-error e monitorando um resíduo (e.g. res = hp - hr); (2) git clone seu repo e tentar ajustar solver settings, e.g. initial guesses do Newton-Raphson (alguma sugestao por onde comecar?). 

Novamente obrigado pela iniciativa e pelo empenho em ter botado o Laine pra funcionar. :)

**Comment by machml** [comment]
Achei interessante também que o solver nao tem problemas em resolver o seguinte equacionamento:

```
T1 = 298
T2 = 400
T3 = 1200

hc3h8_R=NasaSI('H0molar',T1,'C3H8')

ho2_R=NasaSI('H0molar',T2,'O2')
hn2_R=NasaSI('H0molar',T2,'N2')

hco2_P=NasaSI('H0molar',T3,'CO2')
hh2o_P=NasaSI('H0molar',T3,'H2O')
ho2_P=NasaSI('H0molar',T3,'O2')
hn2_P=NasaSI('H0molar',T3,'N2')

a = 5

hp = 3 * hco2_P + 4 * hh2o_P + 3.76 * a * s * hn2_P + a * (s-1) * ho2_P
hr = hc3h8_R + a * s * ( ho2_R + 3.76 * hn2_R )

res = hp - hr
res = 0
```

**Comment by srnogueira** [comment]
Oi Jonas,
Obrigado pela mensagem e por reportar o problema.
Acho que o problema é como a laine tenta simplificar o problema.
No caso, por exemplo, o algoritmo deveria simplificar as equações abaixo em apenas uma

> hp = 3 * hco2_P + 4 * hh2o_P + 3.76 * a * s * hn2_P + a * (s-1) * ho2_P

>  hr = hc3h8_R + a * s * ( ho2_R + 3.76 * hn2_R )

> hp = hr

Mas ele se atrapalha no caminho. Se você trocar as equações por:

> 3 * hco2_P + 4 * hh2o_P + 3.76 * a * s * hn2_P + a * (s-1) * ho2_P=  hc3h8_R + a * s * ( ho2_R + 3.76 * hn2_R )

Então parece resolver.
De qualquer forma é um bug grosseiro que não deveria acontecer.
Só não sei exatamente onde está o erro nas rotinas de substituição. Elas estão super bagunçadas haha.

PS: Eu nunca usei essas funções de comunidade e colaboração do Github, só tenho uma vaga ideia de como funciona. Então me dê uns toques se eu estou fazendo algo errado.

**Comment by srnogueira** [comment]
Acho que consegui arrumar, espero que não tenha quebrado nada no caminho.
O algoritmo tenta interpretar todas as linhas primeiro, pois algumas são muito simples (e.g. "X = 10") e não precisam de um método iterativo para resolver.
As linhas que ele não entende viram equações para o solver. No caso ele estava entendendo a linha "hp = hr" como hp = *objeto hr*, o que não devia acontecer.
Então eu coloquei uma nova excessão nessa parte do código e acho que resolveu.

`		    if (typeof(ans)=="object"){`
`			// Remove object from parser scope (avoid errors)`
`			lhs = aux[j].split('=')[0].trim();`
`			parser.remove(lhs);`
`			// Throw a dummy error`
`			throw Error("Not a real evaluation");`
`		    }`

Obrigado por apontar esse erro Jonas, eu não ia nem notar se você não tivesse falado.
